// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aysatgeriycsosoupwqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5c2F0Z2VyaXljc29zb3Vwd3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjMxNzIsImV4cCI6MjA2NDI5OTE3Mn0.NIsxy-74cEEfzDtua9-S8kLZ2GSvRIv52a7xl81iemk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);